### ISSUE TITLE
Having problems returning image from uploads folder

### ISSUE THREAD

**Issue by Reine0017** [jaewonhimnae/quill-editor-blog#9]
I can successfully upload the image into uploads folder with multer. However, I keep getting a 404 not found error when trying to return the image. May I ask why?

**Comment by Fractal393** [comment]
> I can successfully upload the image into uploads folder with multer. However, I keep getting a 404 not found error when trying to return the image. May I ask why?

Did you find a solution to that problem?

**Comment by Reine0017** [comment]
Hey @Fractal393! Yeah it turns out that its a problem with my own codes and not with this repo hahaa. (My bad)

**Comment by Fractal393** [comment]
> Hey @Fractal393! Yeah it turns out that its a problem with my own codes and not with this repo hahaa. (My bad)

Hi yeah thanks, it was the same thing with me XD
